config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'files/delete'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    get 'page/:page', action: :index, on: :collection
  end
  get 'signup' => 'developers#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :developers, only: %i[new create]
  post 'movie' => 'movies#new'
  get 'movies' => 'movies#index'
end

app/models/developer.rb
# frozen_string_literal: true

# Developer
class Developer < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/developers_controller.rb
# frozen_string_literal: true

# DevelopersController
class DevelopersController < ApplicationController
  def new
    @developer = Developer.new unless Rails.env.production?
  end

  def create
    # 実際には新規登録機能は不要なためproduction環境では機能を無効化
    return if Rails.env.production?

    @developer = Developer.new(user_params)
    if @developer.save
      log_in @developer
      flash[:success] = 'Welcome to the Sample App!'
    end
    render 'new'
  end

  private

  def user_params
    params.require(:developer).permit(:name, :email, :password,
                                      :password_confirmation)
  end
end

app/helpers/developers_helper.rb
# frozen_string_literal: true

# DevelopersHelper
module DevelopersHelper
end

app/views/developers/new.html.erb
<h1>Sign up</h1>
<%= form_for @developer, url: developers_path do |f| %>
    <%= render 'shared/error_messages' %>
    
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>