config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'files/delete'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    get 'page/:page', action: :index, on: :collection
  end
  get 'signup' => 'developers#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :developers, only: %i[new create]
  post 'movie' => 'movies#new'
  get 'movies' => 'movies#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <title>TwitcastingDbApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag %>
</head>

<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light row">
    <%= link_to 'TwitcastingDbApp', users_path, class: 'navbar-brand col-md-9' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse col-md-3" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'ログ一覧', movies_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ファイル削除', files_delete_path, class: 'nav-link', remote: true, data: {confirm: '本当に削除しますか？'}, id: 'deleteFile' %>
          </li>
          <li class="nav-item">
            <%= link_to '戻る', :back, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'サインアウト', logout_path, method: "delete", class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>
<div class="row">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type} col-md-8 mx-auto mt-2") %>
  <% end %>
</div>
<main class="container">
  <%= yield %>
</main>
<%= debug(params) if Rails.env.development? %>
<%= debug(session[:developer_id]) if Rails.env.development? %>
</body>

</html>